series:
  fred:
    - DGS10        # 10y
    - DGS2         # 2y
    - DGS3MO       # 3m bill
    - DFII10       # 10y TIPS (real)
    - NAPM         # ISM PMI (composite)  <-- proxy for New Orders (no API key needed)
    - BAMLH0A0HYM2 # HY OAS
    - SP500
    - DCOILWTICO   # WTI
    - DHHNGSP      # Henry Hub
    - CBBTCUSD     # BTC/USD
    - CBETHUSD     # ETH/USD
    - DTWEXBGS     # Broad $ index (FRED)
  nyfed_tp10: true

tiles:
  y10_green_max: 0.042
  y10_yellow_max: 0.052
  tips_green_max: 0.018
  tips_yellow_max: 0.022
  tp10_green_max: 0.003
  tp10_yellow_max: 0.008
  dxy_green_max: 102.5
  dxy_yellow_max: 104.0
  pmi_green_min: 52.0
  pmi_yellow_min: 50.0
  hyoas_green_max_bps: 325
  hyoas_yellow_max_bps: 400
  curve_green_min_bps: 0
  curve_yellow_min_bps: -30
  wti_green_min: 60
  wti_yellow_min: 50
